# Generated by Django 2.1.15 on 2022-12-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200618_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='people',
            field=models.CharField(default='', max_length=10),
        ),
    ]
